POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo 01",
  "description": "Esse é o vídeo 01",
  "duration": 180
}
###
GET http://localhost:3333/videos
###
PUT http://localhost:3333/videos/721a4004-f876-49e2-9cb7-10283b2dac98
Content-Type: application/json

{
  "title": "Vídeo 02",
  "description": "Esse é o vídeo 02",
  "duration": 180
}
###
DELETE http://localhost:3333/videos/721a4004-f876-49e2-9cb7-10283b2dac98