POST http://localhost:3333/videos
Content-Type: application/json

{
  "title": "Vídeo 01",
  "description": "Esse é o vídeo 01",
  "duration": 180
}
###
GET http://localhost:3333/videos?search=node
###
PUT http://localhost:3333/videos/8c19c498-aa79-4a75-b0f4-60b67c09e9f5
Content-Type: application/json

{
  "title": "Vídeo 03",
  "description": "Esse é o vídeo 01",
  "duration": 180
}
###
DELETE http://localhost:3333/videos/b8a6eeb5-8fd6-46a6-a876-a5a3cf6a51fe